### ISSUE TITLE
something suddenly occurred with the href keyword

### ISSUE THREAD

**Issue by TINYMAHER** [Mastersam07/animeX-pack#2]
![Screenshot 2020-09-30 073847](https://user-images.githubusercontent.com/57438243/94647074-038e5c00-02f0-11eb-9f42-28416443bc7f.png)
no matter what i do , it still gives me that , it was working just fine for a bit then it suddenly kept giving me this error , tried to change location , change anime , change path of python , update python , installing the script again and nothing changes.

any help is appreciated.

**Comment by Mastersam07** [comment]
Hello, seems you've resolved it as you closed the issue. How did you go about it

**Comment by TINYMAHER** [comment]
I just updated some packages that had a resolver problem , but I did it
accidentally while trying to setup another script 😅
